// <auto-generated />
using HBWeekOneAPI.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HBWeekOneAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210922134237_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("HBWeekOneAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sony Xperia L1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Huawei Mate 9 "
                        },
                        new
                        {
                            Id = 3,
                            Name = "Iphone 13"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Redmi Note 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
